name: Update Dune Queries

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-dune-queries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  # Uses a personal access token to push changes

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Convert Notebook to Python
        run: jupyter nbconvert --to script queries_backup.ipynb
   
        
      - name: Update Queries
        run: |
          python queries_backup.py
          git add .
          if git diff --cached --quiet; then
            echo "No changes detected. Exiting..."
            exit 0
          fi

      - name: Commit and Push Changes to a New Branch
        run: |
          BRANCH_NAME="update-dune-queries-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          git commit -m "Auto-update Dune SQL queries"
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ steps.commit-changes.outputs.branch }}
          base: main
          title: "Auto-update Dune SQL queries"
          body: "This PR contains the latest updates to Dune SQL queries."
          labels: automated
          assignees: ppclunghe
          reviewers: ppclunghe
          token: ${{ secrets.GH_PAT }}

      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
          merge-method: squash
          token: ${{ secrets.GH_PAT }}
